# Generated by Django 3.2.5 on 2021-08-02 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteBoardApp', '0002_auto_20210728_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='text',
        ),
        migrations.AlterField(
            model_name='note',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 2, 19, 53, 47, 869402), null=True, verbose_name='Дата и время выполнения'),
        ),
    ]
